const mongoose = require("mongoose");
const { Schema } = mongoose;

const TICKET_STATUSES = [
  "DIAGNOSIS",
  "IN_PROGRESS",
  "WAITING_PART",
  "RESOLVED",
  "CANCELLED",
  "ARCHIVED",
];

const TICKET_PRIORITIES = ["LOW", "MEDIUM", "HIGH", "URGENT"];

const statusHistorySchema = new Schema(
  {
    timestamp: {
      type: Date,
      default: Date.now,
    },
    newStatus: {
      type: String,
      enum: TICKET_STATUSES,
      required: true,
    },
    note: {
      type: String,
      trim: true,
    },
  },
  { _id: false },
);

const replacementItemSchema = new Schema(
  {
    componentName: {
      type: String,
      required: true,
      trim: true,
    },
    quantity: {
      type: Number,
      required: true,
      min: 1,
      default: 1,
    },
    note: {
      type: String,
      trim: true,
    },
  },
  { _id: false },
);

const serviceTicketSchema = new Schema(
  {
    ticketNumber: {
      type: String,
      unique: true,
      trim: true,
      index: true,
    },
    customerId: {
      type: Schema.Types.ObjectId,
      ref: "Customer",
      required: true,
      index: true,
    },
    deviceId: {
      type: Schema.Types.ObjectId,
      ref: "Device",
      required: true,
      index: true,
    },
    technicianId: {
      type: Schema.Types.ObjectId,
      ref: "User",
      default: null,
      index: true,
    },
    initialComplaint: {
      type: String,
      required: [true, "Initial complaint is required"],
      trim: true,
    },
    priority: {
      type: String,
      enum: TICKET_PRIORITIES,
      default: "MEDIUM",
      index: true,
    },
    status: {
      type: String,
      enum: TICKET_STATUSES,
      required: true,
      default: "DIAGNOSIS",
      index: true,
    },
    resolvedAt: {
      type: Date,
      default: null,
    },
    technicianDiagnosis: {
      type: String,
      trim: true,
      default: null,
    },
    technicianSolution: {
      type: String,
      trim: true,
      default: null,
    },
    statusHistory: { type: [statusHistorySchema], default: [] },
    replacementItems: { type: [replacementItemSchema], default: [] },
  },
  {
    timestamps: true,
  },
);

serviceTicketSchema.pre("save", async function (next) {
  if (!this.isNew || this.ticketNumber) return next();

  if (this.isNew && (!this.statusHistory || this.statusHistory.length === 0)) {
    this.statusHistory = [
      {
        newStatus: this.status,
        note: "Ticket generated by system.",
      },
    ];
  }

  try {
    const year = new Date().getFullYear();
    const prefix = `SRV-${year}-`;

    const lastTicket = await this.constructor
      .findOne({ ticketNumber: new RegExp(`^${prefix}`) })
      .sort({ ticketNumber: -1 })
      .select("ticketNumber")
      .lean();

    let sequence = 1;
    if (lastTicket && lastTicket.ticketNumber) {
      const lastSeq = parseInt(lastTicket.ticketNumber.split("-")[2], 10);
      sequence = lastSeq + 1;
    }

    this.ticketNumber = `${prefix}${String(sequence).padStart(6, "0")}`;
    next();
  } catch (error) {
    next(error);
  }
});

/**
 *
 * DTO Mapper: Mengkonversi dokumen MongoDB ke format JSON yang strict
 *
 */
const toTicketDto = (doc) => {
  return {
    ticketId: doc._id.toString(),
    ticketNumber: doc.ticketNumber,
    status: doc.status,
    priority: doc.priority,
    initialComplaint: doc.initialComplaint,
    createdAt: doc.createdAt,
    updatedAt: doc.updatedAt,
    resolvedAt: doc.resolvedAt || null,
    technicianDiagnosis: doc.technicianDiagnosis || null,
    technicianSolution: doc.technicianSolution || null,

    customer: doc.customerId?._id
      ? {
          customerId: doc.customerId._id.toString(),
          name: doc.customerId.name,
          phone: doc.customerId.phone || null,
        }
      : doc.customerId,

    device: doc.deviceId?._id
      ? {
          deviceId: doc.deviceId._id.toString(),
          type: doc.deviceId.type || null,
          brand: doc.deviceId.brand || null,
          model: doc.deviceId.model || null,
          serialNumber: doc.deviceId.serialNumber || null,
        }
      : doc.deviceId,

    technician: doc.technicianId?._id
      ? {
          technicianId: doc.technicianId._id.toString(),
          name: doc.technicianId.name || null,
        }
      : doc.technicianId,

    statusHistory: doc.statusHistory.map((h) => ({
      timestamp: h.timestamp,
      newStatus: h.newStatus,
      note: h.note,
    })),

    replacementItems: doc.replacementItems.map((item) => ({
      componentName: item.componentName,
      quantity: item.quantity,
      note: item.note || null,
    })),
  };
};

const ServiceTicket = mongoose.model("ServiceTicket", serviceTicketSchema);

module.exports = {
  ServiceTicket,
  TICKET_STATUSES,
  TICKET_PRIORITIES,
  toTicketDto,
};
